<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>AdminLTE 2 | Dashboard</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <script src="https://code.jquery.com/jquery-1.11.2.js"></script>
    <?php echo $this->headLink()
                    ->appendStylesheet($this->basePath('bootstrap/css/bootstrap.min.css'))
                    ->appendStylesheet('https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css')
                    ->appendStylesheet('http://code.ionicframework.com/ionicons/2.0.0/css/ionicons.min.css')
                    ->appendStylesheet($this->basePath('plugins/morris/morris.css'))
                    ->appendStylesheet($this->basePath('plugins/jvectormap/jquery-jvectormap-1.2.2.css')) 
                    ->appendStylesheet($this->basePath('plugins/daterangepicker/daterangepicker-bs3.css'))
                    ->appendStylesheet($this->basePath('dist/css/AdminLTE.min.css'))
                    ->appendStylesheet($this->basePath('dist/css/skins/_all-skins.min.css'))
                    ?>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>
  <body class="skin-blue">
    <div class="wrapper">
      
      <header class="main-header">
        <!-- Logo -->
        <a class="logo">K12 Educational</a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top" role="navigation">
          <!-- Sidebar toggle button-->
          <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
          </a>
          <!-- Navbar Right Menu -->
          <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
              <!-- Messages: style can be found in dropdown.less-->
              <li class="dropdown messages-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" onClick="$('#chat').fadeToggle();">
                  <i class="fa fa-envelope-o"></i>
                </a>
              </li>
              <!-- Notifications: style can be found in dropdown.less -->
              <li class="dropdown notifications-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <i class="fa fa-bell-o"></i>
                </a>
                <ul class="dropdown-menu">
                  <li class="header">You have 10 notifications</li>
                  <li>
                    <!-- inner menu: contains the actual data -->
                    <ul class="menu">
                      <li>
                        <a href="#">
                          <i class="fa fa-users text-aqua"></i> 5 new members joined today
                        </a>
                      </li>
                      <li>
                        <a href="#">
                          <i class="fa fa-warning text-yellow"></i> Very long description here that may not fit into the page and may cause design problems
                        </a>
                      </li>
                      <li>
                        <a href="#">
                          <i class="fa fa-users text-red"></i> 5 new members joined
                        </a>
                      </li>

                      <li>
                        <a href="#">
                          <i class="fa fa-shopping-cart text-green"></i> 25 sales made
                        </a>
                      </li>
                      <li>
                        <a href="#">
                          <i class="fa fa-user text-red"></i> You changed your username
                        </a>
                      </li>
                    </ul>
                  </li>
                  <li class="footer"><a href="#">View all</a></li>
                </ul>
              </li>
              <!-- User Account: style can be found in dropdown.less -->
              <?php echo $this->UserMenu() ?>
            </ul>
          </div>
        </nav>
      </header>
      <!-- Left side column. contains the logo and sidebar -->
      <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
          <!-- search form -->
          <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
              <input type="text" name="q" class="form-control" placeholder="Search..."/>
              <span class="input-group-btn">
                <button type='submit' name='search' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i></button>
              </span>
            </div>
          </form>
          <!-- /.search form -->
          <!-- sidebar menu: : style can be found in sidebar.less -->
          <ul class="sidebar-menu">
            <li class="header">Control Panel</li></li>
            <li>
              <a href="#">
                <i class="fa fa-users"></i> <span>Utenti</span>
              </a>
            </li>
            <li class="treeview">
              <a href="#">
                <i class="fa fa-files-o"></i>
                <span>Esercizi</span>
              </a>
              <ul class="treeview-menu">
                <li><a href="<?php echo $this->url('question') ?>"><i class="fa fa-circle-o"></i> Domande</a></li>
                <li><a href="<?php echo $this->url('questionnaire') ?>"><i class="fa fa-circle-o"></i> Questionari</a></li>
              </ul>
            </li>
        </ul>
        </section>
        <!-- /.sidebar -->
      </aside>

      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        <?php echo $this->content ?>
        <iframe id="chat" style="display:none;right:15px;top:60px;border: 0px solid black;position:fixed;height:400px;width:340px;"src="http://node.server.educationet.tk/?id=<?php echo $this->UserIdentity()->firstName.'%20'.$this->UserIdentity()->lastName ?>"></iframe>
      </div><!-- /.content-wrapper -->
    </div><!-- ./wrapper -->
    
    <?php echo $this->headScript()
                    ->appendFile($this->basePath('plugins/jQuery/jQuery-2.1.3.min.js'))
                    ->appendFile($this->basePath('bootstrap/js/bootstrap.min.js'))
                    ->appendFile($this->basePath('plugins/fastclick/fastclick.min.js'))
                    ->appendFile($this->basePath('dist/js/app.min.js'))
                    ->appendFile($this->basePath('plugins/sparkline/jquery.sparkline.min.js'))
                    ->appendFile($this->basePath('plugins/jvectormap/jquery-jvectormap-1.2.2.min.js'))
                    ->appendFile($this->basePath('plugins/jvectormap/jquery-jvectormap-world-mill-en.js'))
                    ->appendFile($this->basePath('plugins/daterangepicker/daterangepicker.js'))
                    ->appendFile($this->basePath('plugins/datepicker/bootstrap-datepicker.js'))
                    ->appendFile($this->basePath('plugins/iCheck/icheck.min.js'))
                    ->appendFile($this->basePath('plugins/slimScroll/jquery.slimscroll.min.js'))
                    ->appendFile($this->basePath('plugins/chartjs/Chart.min.js'))
                    ->appendFile($this->basePath('dist/js/pages/dashboard2.js'))
                    ->appendFile($this->basePath('dist/js/demo.js')); ?>
    <script language="javascript">
      //fadeout chat iframe on outside click
      $(document).on('click', function(e) {
          if ( ! $(e.target).closest('#chat').length ) 
               $('#chat').fadeOut();
      });
    </script>
  </body>
</html>