<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>K12 Educational | Log in</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <?php echo $this->headLink()
                    ->appendStylesheet($this->basePath('bootstrap/css/bootstrap.min.css'))
                    ->appendStylesheet('https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css')
                    ->appendStylesheet($this->basePath('dist/css/AdminLTE.min.css'))
                    ->appendStylesheet($this->basePath('plugins/iCheck/square/blue.css'))
                    ?>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>
  <body class="login-page">
    <?php echo $this->content ?>
    <?php echo $this->headScript()
                    ->appendFile($this->basePath('plugins/jQuery/jQuery-2.1.3.min.js'))
                    ->appendFile($this->basePath('bootstrap/js/bootstrap.min.js'))
                    ->appendFile($this->basePath('plugins/iCheck/icheck.min.js')) ?>
    <script>
      $(function () {
        $('input').iCheck({
          checkboxClass: 'icheckbox_square-blue',
          radioClass: 'iradio_square-blue',
          increaseArea: '20%' // optional
        });
      });
    </script>
  </body>
</html>