<?php
$form = $this->loginForm;
$form->setAttribute('method', 'post');
$form->setAttribute('action', $this->url('authentication/login'));
$form->prepare();
?>
<div class="login-box">
      <div class="login-logo">
        <a>K12 Educational</a>
      </div><!-- /.login-logo -->
      <div class="login-box-body">
        <p class="login-box-msg">Sign in to start your session</p>
          <?php echo $this->form()->openTag($form) ?>
          <div class="form-group has-feedback">
            <?php echo $this->formInput($form->get('identity')) ?>
            <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
          </div>
          <div class="form-group has-feedback">
            <?php echo $this->formInput($form->get('password')) ?>
            <span class="glyphicon glyphicon-lock form-control-feedback"></span>
          </div>
          <div class="row">
            <div class="col-xs-8">    
              <div class="checkbox icheck">
                <label>
                  <input type="checkbox"> Remember Me
                </label>
              </div>                        
            </div><!-- /.col -->
            
	          <?php echo $this->formHidden($form->get('csrf')); ?>
            <div class="col-xs-4">
              <?php echo $this->formSubmit($form->get('submit')) ?>
            </div><!-- /.col -->
          </div>
        <?php echo $this->form()->closeTag() ?>

        <a href="#">I forgot my password</a><br>

      </div><!-- /.login-box-body -->
    </div><!-- /.login-box -->