<section class="content">
	<div class="row">
        <?php if ($this->success === true) { ?>
            <div class="col-md-12">
              <div class="alert alert-success alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <h4>	<i class="icon fa fa-check"></i> Operazione avvenuta con successo!</h4>
                	Domande assegnate con successo. <a href="<?php echo $this->url('questionnaire') ?>">Indietro</a>
              </div>
            </div><!-- /.col -->
          <?php } else if ($this->success === false){ ?>
          	<div class="col-md-12">
              <div class="alert alert-danger alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <h4>	<i class="icon fa fa-times"></i> Operazione non riuscita.</h4>
                Errore durante l'assegnazione delle domande. <a href="<?php echo $this->url('questionnaire') ?>">Indietro</a>
              </div>
            </div>
          <?php } ?>
	</div>
	<div class="row">
		<div class="col-md-12">
        	<div class="box">
                <div class="box-header with-border">
                  <h3 class="box-title">Assegna domande</h3>
                </div><!-- /.box-header -->
                <div class="box-body">
                <?php $form = $this->form->setAttribute('action', $this->url('questionnaire', array('action' => 'assignQuestions')))->prepare();
                	  echo $this->form()->openTag($form);
                ?>
                  <div class="row">
                    <!-- left column -->
                    <div class="col-md-3">
                      <!-- general form elements -->
                      <div class="box-body">
                        <div class="form-group">
                        	<label>Questionario</label>
                        	<div class="radio">
	                          <?php $this->formRadio()->setSeparator('</div><div class="radio">');
	                          echo $this->formRadio($form->get('questionnaire')) ?>
	                        </div>
                        </div>
                      </div>
                    </div>
                    <div class="col-md-9">
                      <!-- general form elements -->
                      <div class="box-body">
                        <div class="form-group">
                        	<label>Domande da assegnare</label>
                          <?php echo $this->formSelect($form->get('questions')) ?>
                          <br>
                          <?php echo $this->formSubmit($form->get('submit')) ?>
                        </div>
                    </div>
                  </div>
                  <?php echo $this->formHidden($form->get('csrf'));
                  		echo $this->form()->closeTag(); ?>
                </div><!-- ./box-body -->
              </div><!-- /.box -->
            </div><!-- /.col -->
          </div><!-- /.row -->
</section>