<section class="content">
	<div class="row">
        <?php if ($this->success === true) { ?>
            <div class="col-md-12">
              <div class="alert alert-success alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <h4>	<i class="icon fa fa-check"></i> Operazione avvenuta con successo!</h4>
                Il questionario &egrave stato creato. <a href="<?php echo $this->url('questionnaire', array('action' => 'assignQuestions')) ?>">Assegna Domande</a>
              </div>
            </div><!-- /.col -->
          <?php } else if ($this->success === false){ ?>
          	<div class="col-md-12">
              <div class="alert alert-danger alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <h4>	<i class="icon fa fa-times"></i> Operazione non riuscita.</h4>
                Il questionario non &egrave stato creato. <a href="<?php echo $this->url('question') ?>">Riprova</a>
              </div>
            </div>
          <?php } ?>
	</div>
	<div class="row">
		<div class="col-md-12">
        	<div class="box collapsed-box">
                <div class="box-header with-border">
                  <h3 class="box-title">Aggiungi questionario</h3>
                  <div class="box-tools pull-right">
                    <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"> Espandi</i></button>
                    <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"> Rimuovi</i></button>
                  </div>
                </div><!-- /.box-header -->
                <div class="box-body">
                <?php $form = $this->form->setAttribute('action', $this->url('questionnaire', array('action' => 'create')))->prepare();
                	  echo $this->form()->openTag($form);
                ?>
                  <div class="row">
                    <!-- left column -->
                    <div class="col-md-6">
                      <!-- general form elements -->
                      <div class="box-body">
                        <div class="form-group">
                        	<label>Nome</label>
                          <?php echo $this->formRow($form->get('name')) ?>
                        </div>
                    </div>
                    <div class="col-md-6">
                      <!-- general form elements -->
                      <div class="box-body">
                        <div class="form-group">
                          <?php echo $this->formSubmit($form->get('submit')) ?>
                        </div>
                    </div>
                  </div>
                  <?php echo $this->formHidden($form->get('csrf'));
                  		echo $this->form()->closeTag(); ?>
                </div><!-- ./box-body -->
              </div><!-- /.box -->
            </div><!-- /.col -->
          </div><!-- /.row -->
</section>