		<section class="content">
			<div class="row">
            <div class="col-md-12">
        	<div class="box collapsed-box">
                <div class="box-header with-border">
                  <h3 class="box-title">Aggiungi questionario</h3>
                  <div class="box-tools pull-right">
                    <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"> Espandi</i></button>
                    <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"> Rimuovi</i></button>
                  </div>
                </div><!-- /.box-header -->
                <div class="box-body">
                <?php $form = $this->addForm->setAttribute('action', $this->url('questionnaire', array('action' => 'create')))->prepare();
                	  echo $this->form()->openTag($form);
                ?>
                  <div class="row">
                    <!-- left column -->
                    <div class="col-md-6">
                      <!-- general form elements -->
                      <div class="box-body">
                        <div class="form-group">
                        	<label>Nome</label>
                          <?php echo $this->formRow($form->get('name')) ?>
                        </div>
                      </div>
                    </div>
                    <div class="col-md-6">
                      <!-- general form elements -->
                      <div class="box-body">
                        <div class="form-group">
                          <?php echo $this->formSubmit($form->get('submit')) ?>
                        </div>
                      </div>
                    </div>
                  </div>
                  <?php echo $this->formHidden($form->get('csrf'));
                  		echo $this->form()->closeTag(); ?>
                </div><!-- ./box-body -->
              </div><!-- /.box -->
            </div><!-- /.col -->
          </div><!-- /.row -->
            <div class="row">
                    <div class="col-md-12">
        	<div class="box collapsed-box">
                <div class="box-header with-border">
                  <h3 class="box-title">Assegna domande al questionario</h3>
                  <div class="box-tools pull-right">
                    <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"> Espandi</i></button>
                    <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"> Rimuovi</i></button>
                  </div>
                </div><!-- /.box-header -->
                <div class="box-body">
                <?php $form = $this->assignForm->setAttribute('action', $this->url('questionnaire', array('action' => 'assignQuestions')))->prepare();
                	  echo $this->form()->openTag($form);
                ?>
                  <div class="row">
                    <!-- left column -->
                    <div class="col-md-3">
                      <!-- general form elements -->
                      <div class="box-body">
                        <div class="form-group">
                        	<label>Questionario</label>
                        	<div class="radio">
	                          <?php $this->formRadio()->setSeparator('</div><div class="radio">');
	                          echo $this->formRadio($form->get('questionnaire')) ?>
	                        </div>
                        </div>
                      </div>
                    </div>
                    <div class="col-md-9">
                      <!-- general form elements -->
                      <div class="box-body">
                        <div class="form-group">
                        	<label>Domande da assegnare</label>
                          <?php echo $this->formSelect($form->get('questions')) ?>
                          <br>
                          <?php echo $this->formSubmit($form->get('submit')) ?>
                        </div>
                    </div>
                  </div>
                  <?php echo $this->formHidden($form->get('csrf'));
                  		echo $this->form()->closeTag(); ?>
                </div><!-- ./box-body -->
              </div><!-- /.box -->
            </div><!-- /.col -->
          </div><!-- /.row -->
         </section>